
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION

before_script:
  - sudo -u postgres createuser -s "$USER"

env:
  matrix:
    - PGVERSION=9.2
    - PGVERSION=9.3
    - PGVERSION=9.4
    - PGVERSION=9.5
    - PGVERSION=9.6
    - PGVERSION=10

dist: trusty

sudo: required

language: c

compiler:
  - gcc

script:
  - make && sudo make install && make installcheck

after_script:
  - cat regression.diffs || true
  
