
addons:
  apt:
    sources:
    - sourceline: "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 11"
      key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-${PG:?} postgresql-server-dev-${PG:?}

before_script:
  - sudo -u postgres createuser -s "$USER"

env:
  matrix:
    - PG=9.2
    - PG=9.3
    - PG=9.4
    - PG=9.5
    - PG=9.6
    - PG=10
    - PG=11

dist: trusty

sudo: required

language: c

compiler:
  - gcc

script:
  - make && sudo make install && make installcheck

after_script:
  - cat regression.diffs || true
  
